import Head from 'next/head'
import styles from '../styles/home.module.css'

import UploadButton from '../lib/components/uploadButton';
import Copyright from '../lib/components/copyright';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <img src="/logo.svg"/>
        <UploadButton/>
        <Copyright/>
      </main>
    </>
  )
}
